name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  semantic:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Install
        run: |
          uv venv
          uv pip install -e ".[dev]"
      - name: Lint
        run: |
          uv run ruff format --check .
          uv run ruff check .
      - name: Typecheck
        run: uv run mypy src
      - name: Test
        run: uv run pytest --cov=src --cov-report=term-missing --cov-fail-under=100
